### ISSUE TITLE
[doc] Write vim doc

### ISSUE THREAD

**Issue by nullchilly** [nullchilly/cpeditor.nvim#9]
Or find a way to auto-generate it.

**Comment by nullchilly** [comment]
@huylg Can you help me write a vim doc that point directly to the readme? I couldn't make `:h cpeditor` work for some reason.

https://github.com/nullchilly/cpeditor.nvim/blob/main/doc/cpeditor.txt

**Comment by huylg** [comment]
okay, I will check it.

**Comment by nullchilly** [comment]
It works 🚀
